# bitrix_activity_webhook.py
from fastapi import APIRouter, Request
import requests
from datetime import datetime
from config import supabase
from helpers.retry_manager import cancel_retry_for_lead

router = APIRouter()


@router.post("/bitrix-activity-webhook")
async def bitrix_activity_webhook(request: Request):
    """
    Webhook triggered when ANY activity is created in Bitrix.
    We use it to detect if:
        - A HUMAN agent made a manual phone call (Acefone / Mobile / Call Center)
        - Lead or Deal received manual attention → retry auto-calls must stop.
    """
    data = await request.json()
    print("📥 Bitrix Activity Webhook Received:", data)

    fields = data.get("data", {}).get("FIELDS", {})
    activity_id = fields.get("ID")
    owner_type = fields.get("OWNER_TYPE_ID")  # 1=Lead, 2=Deal
    owner_id = fields.get("OWNER_ID")
    provider_id = fields.get("PROVIDER_ID")   # telephony / voximplant / crm / bolna
    result_status = fields.get("RESULT_STATUS")  # success/missed/busy/etc
    subject = fields.get("SUBJECT", "")

    # Safety checks
    if not owner_type or not owner_id:
        return {"status": "ignored", "reason": "No owner info"}

    # Detect LEAD or DEAL
    lead_id = None

    # If activity belongs to a LEAD directly
    if owner_type == "1":
        lead_id = owner_id

    # If activity belongs to a DEAL → fetch its lead from SUPABASE mapping
    elif owner_type == "2":
        try:
            mapping = supabase.table("deal_lead_mapping") \
                              .select("lead_id") \
                              .eq("deal_id", owner_id) \
                              .execute()
            if mapping.data:
                lead_id = mapping.data[0]["lead_id"]
        except Exception as e:
            print("⚠️ Mapping fetch error:", e)

    if not lead_id:
        return {"status": "ignored", "reason": "Lead ID not found"}

    # -----------------------------
    # IGNORE BOT-GENERATED ACTIVITY
    # -----------------------------
    if provider_id and provider_id.lower() in ["bolna", "ai", "automation"]:
        return {"status": "ignored", "reason": "Activity belongs to Bolna bot"}

    if "bolna" in (subject or "").lower():
        return {"status": "ignored", "reason": "Activity auto-generated by bot"}

    # ------------------------------
    # DETECT MANUAL HUMAN PHONE CALL
    # ------------------------------
    is_manual_call = False

    # Provider ID for human telephony systems
    HUMAN_PROVIDERS = ["telephony", "voximplant", "asterisk", "call"]  # add more if needed

    if provider_id and provider_id.lower() in HUMAN_PROVIDERS:
        is_manual_call = True

    # Subject text also helps detect manual calls
    if any(w in subject.lower() for w in ["call", "phone", "callback", "dial"]):
        is_manual_call = True

    # If RESULT_STATUS = success → call was connected
    if result_status and result_status.lower() in ["success", "answered"]:
        is_manual_call = True

    if not is_manual_call:
        return {"status": "ignored", "reason": "Activity was not a manual call"}

    # ------------------------------
    # MANUAL CALL DETECTED → CANCEL RETRIES
    # ------------------------------
    print(f"📞 HUMAN manual call detected for LEAD {lead_id}. Cancelling retries.")

    cancel_retry_for_lead(lead_id, reason="manual_call_detected")

    # Log event to Supabase
    try:
        supabase.table("manual_call_logs").insert({
            "timestamp": datetime.utcnow().isoformat(),
            "lead_id": lead_id,
            "activity_id": activity_id,
            "provider_id": provider_id,
            "result_status": result_status,
            "subject": subject
        }).execute()
    except Exception as e:
        print("❌ Failed to log manual call:", e)

    return {"status": "success", "action": "retry_cancelled", "lead_id": lead_id}
